PR Bonus 0
made-ml-in-prod-2021/novokolg pull request #1
Opened 2021-04-04 18:33 UTC by novokolg

2021-04-04 20:18 UTC, Mikhail-M reviewed
А файлики от idea точно нужно?

2021-04-04 21:01 UTC, novokolg commented
> А файлики от idea точно нужно?

Спасибо! действительно пропустила, что эти файлики нам не нужны, удалены.

2021-04-05 11:15 UTC, Mikhail-M commented
> > А файлики от idea точно нужно?
> 
> Спасибо! действительно пропустила, что эти файлики нам не нужны, удалены.
> 

у вас теперь конфликт((

2021-04-05 17:34 UTC, Mikhail-M approved these changes

2021-04-05 17:35 UTC, Mikhail-M requested changes
теперь readme нет

2021-04-05 21:15 UTC, novokolg commented
> теперь readme нет

Решила все потереть и сделать заново. Надеюсь, что сейчас все заработает.
Интересно, а в процессе работы все ровно так и случается?
и разговор про изменения и поправки ведется в PR ветке?

2021-04-07 09:55 UTC, Mikhail-M approved these changes

2021-04-07 10:59 UTC, merged